### ISSUE TITLE
 React DOM crashes when <option> contains three interpolated value if one is a conditional. 

### ISSUE THREAD

**Issue by ZhangYiJiang** [facebook/react#11911]
**Do you want to request a *feature* or report a *bug*?** 

Bug 

**What is the current behavior?**

React DOM crashes when `<option>` contains three interpolated value if one is a conditional. 

Reproduction: https://jsfiddle.net/0opjvycp/ 

1. Change the value of the `<select>`
2. React crashes with `NotFoundError: Node was not found` 

From what I can tell, the conditional value is necessary, and it must be three interpolated values. 

**What is the expected behavior?**

React should not crash. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React DOM 16.2 and 16.0. I think this worked in 15.6 - https://jsfiddle.net/mrwkmuqc/ does not crash

**Comment by gaearon** [comment]
Tagging as good first issue.

**Comment by mannanali413** [comment]
@gaearon i can take this up :)

**Comment by jorrit** [comment]
Could this be related to #11602 ?

**Comment by gaearon** [comment]
@mannanali413 Any progress?

**Comment by avinashdvv** [comment]
Hay
I wanted to solve this issue. but the problem is, **i am kind of new to this** 
when i try to test the current test cases of ReactDOMOptions ``react/packages/react-dom/src/__tests__$ jest ReactDOMOption-test.js `` 
i am getting this error.
```
  ● ReactDOMOption › should flatten children to a string

    Cannot find module 'react' from 'ReactDOMOption-test.js'
      
      at Resolver.resolveModule (../../../../.nvm/versions/node/v7.10.1/lib/node_modules/jest/node_modules/jest-resolve/build/index.js:191:17)
      at Object.<anonymous> (src/__tests__/ReactDOMOption-test.js:18:13)

```

**Comment by kevinzwhuang** [comment]
@gaearon I experienced this regression myself yesterday when upgrading from 15.4.2 to 16.2.0.
Here's a simple repro of the problem I was seeing:
https://jsfiddle.net/qkc4eyqe/1/

Same issue - different error message:
`Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

I'm not sure if @mannanali413 is still working on a fix for this, but I can take a closer look later today too.

----
To anyone else experiencing this problem, the only workaround I've found so far is to remove the conditional logic (at least until a fix is found).

**Comment by gaearon** [comment]
@kevinzwhuang Would you like to work on figuring out the fix?

**Comment by kevinzwhuang** [comment]
Sure @gaearon I can work on finding a fix.

Did some digging in devtools
Here's some of my findings:

------------------------------

`parentInstance`: Note the childNodes is a single element of the flattened text
![image](https://user-images.githubusercontent.com/7256178/34635153-5e11e3fe-f240-11e7-9f24-9f465427cc38.png)

`child` to be removed - Since there's a mismatch with the flattened childNodes, 
![image](https://user-images.githubusercontent.com/7256178/34635157-66ef5bb4-f240-11e7-869d-269bd3411b7a.png)

-------------------------------

What we should be seeing is 4 elements in the childNodes array, instead of a single flattened text element - this might have something to do with #11602 like @jorrit mentioned

**Comment by avinashdvv** [comment]
while running ``yarn build`` i am getting below error while trying to do work on this issue
```
  throw err;
  ^

Error: Cannot find module 'react-dom/src/events/EventListener'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.keys.forEach.srcModule (/home/nanohealth/Projects/react/scripts/rollup/plugins/use-forks-plugin.js:35:15)
    at Array.forEach (<anonymous>)
    at useForks (/home/nanohealth/Projects/react/scripts/rollup/plugins/use-forks-plugin.js:32:22)
    at getPlugins (/home/nanohealth/Projects/react/scripts/rollup/build.js:206:5)
    at createBundle (/home/nanohealth/Projects/react/scripts/rollup/build.js:359:14)
    at buildEverything (/home/nanohealth/Projects/react/scripts/rollup/build.js:469:11)
    at <anonymous>
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
sorry for the trouble i am pretty much new this

**Comment by avinashdvv** [comment]
@kevinzwhuang can you make a video or a blog post about how did u solve this issue once u solved this.
try to make a video if possible

**Comment by kevinzwhuang** [comment]
Getting closer to finding the root of the problem by running this code with v15 - it looks like what changed from 15/stack to 16/fiber for this operation is that:
in v15, it would execute `setTextContent` to update the `<option>` text for all cases.
in v16, it executes 'removeChild` or `insertBefore`, or whatever variation of the operation where ReactDOM assumes text nodes should be added or removed - when in fact there shouldn't be more than 1 child node because it's flattened in `ReactDOMFiberOption` (option text nodes were also flattened before in v15, so flattening might be not the issue here)
(whereas this is the normal set of operations for generic components in 15 and 16 because text nodes aren't flattened in other components)

@gaearon - I think the solution has something to do with going back to the old behavior of doing `setTextContent` for `<option>` updates - I'm not sure yet how to go about doing this yet, but this is a step closer to finding it.

**Comment by gaearon** [comment]
Sounds good. I really haven't dug into that code but happy to review a PR once you have something that works.

**Comment by stephenkingsley** [comment]
I think function `insertBefore` has something strange.
```js
insertBefore: function (parentInstance, child, beforeChild) {
  parentInstance.insertBefore(child, beforeChild);
},
```
That is correct , if I use `parentInstance.childNodes[0]` instead of `beforeChild`. Like this:
```js
insertBefore: function (parentInstance, child, beforeChild) {
  parentInstance.insertBefore(child, parentInstance.childNodes[0]);
},
```

**Comment by stephenkingsley** [comment]
@gaearon would you please code review?

**Comment by cvlab** [comment]
I have the same problem with this code
```
<select>
	{ this.state.option === 'first' ?
		<option>{ '' } a</option>
		:
		<option></option>
	}
</select>
```
or
```
<option><br/> a</option>
:
<option></option>
```
because React try to delete each node from `option`

@kevinzwhuang my workaround is to use unique keys 
https://jsfiddle.net/qkc4eyqe/5/ or https://jsfiddle.net/qkc4eyqe/8/

**Comment by itssumitrai** [comment]
Got the same issue with `<span>`, any update on the fix ?

**Comment by dgrcode** [comment]
I'm hitting this too

**Comment by gaearon** [comment]
@itssumitrai This issue is about `option`. If you have a problem with some other tag please file a new issue with a reproducing example.

@dgrcode Knowing that you hit it too doesn't add anything to this conversation. Comments notify everybody subscribed to this thread so it's best to avoid commenting if it doesn't add new info. If you'd like to share more details, or help get it fixed, please let us know!

**Comment by gaearon** [comment]
If someone wants to take another look at https://github.com/facebook/react/pull/12078 and specifically https://github.com/facebook/react/pull/12078#issuecomment-361343352 you're most welcome to do it. That will likely lead us closer to fixing this.

**Comment by Slowyn** [comment]
@gaearon Hi Dan! I would like to investigate into this problem and try to help with fix.

**Comment by gaearon** [comment]
Sounds great! This should be a good starting point: https://github.com/facebook/react/pull/12078#issuecomment-361343352

**Comment by Slowyn** [comment]
@gaearon Hi Dan!
I did some research and that's what I have at the moment. Basically, I just confirm @kevinzwhuang conclusions.
1. A fiber of text inside of option contains `stateNode` without a parentNode.
2. It happens because of flattening children into an `option`.
3. this bug isn't reproduced if I replace children flattening with filtering an array. But this produce new bugs and tests are failed, so it doesn't fit as a decision.
4. Also, the bug isn't reproduced when you use a construction like this `{condition ? 'renderString' ''}`. I mean if not use `null` or  'false' (`{condition && 'renderString'}`).

I think the easiest solution would be a changing of flattening (or replacing) in a right way. As I get it an `option` expects one string as a child, but I'm not sure why we need it now when fiber landed 🤔 

By the way, it's cool to dip into react sources :)

**Comment by gaearon** [comment]
>I think the easiest solution would be a changing of flattening (or replacing) in a right way.

Sounds good to me, wanna try it?

**Comment by Slowyn** [comment]
I have tried to change flattening, but it didn't fix all problems and became a reason for new issues.
Flattening cause different states. DOM has flattened children, while fiber contains all children.
The other possible solution is to allow react to set text content to option as it does to a textarea. It solves all problems, but there is no warning about incorrect children inside because validateDomNesting is called.

**Comment by Slowyn** [comment]
@gaearon Hi, Dan!
I've created a PR that solves the issue. I've added example into fixtures so it would be easy to test.
Let's discuss this solution :)

**Comment by gaearon** [comment]
Fixed by @Slowyn

**Comment by krishnaTORQUE** [comment]
> @gaearon I experienced this regression myself yesterday when upgrading from 15.4.2 to 16.2.0.
> Here's a simple repro of the problem I was seeing:
> https://jsfiddle.net/qkc4eyqe/1/
> 
> Same issue - different error message:
> `Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`
> 
> I'm not sure if @mannanali413 is still working on a fix for this, but I can take a closer look later today too.
> 
> To anyone else experiencing this problem, the only workaround I've found so far is to remove the conditional logic (at least until a fix is found).

after update 16.13.1
I am getting the same error

does anyone found any solution ?
