### PR TITLE
Ensure FullPageComponents are treated as DOM components

### LINKED ISSUE #3421: Bug with find* and scry* methods in TestUtils with React 0.13.0
I’ve tried to update from react 0.12.2 to 0.13.0 which caused several unit tests of my project to fail. I use react to render html on the server side, this includes the basic html structure like `<head>`, `<title>` and `<base>` elements. All unit tests dealing with such elements are failing with react 0.13.0 but they worked fine with 0.12.2.

Here is a minimal example `test.js`:
```js
'use strict';

var React = require('react'),
    ReactAddons = require('react/addons'),
    TestUtils = ReactAddons.addons.TestUtils,
    jsdom = require('jsdom');

global.document = jsdom.jsdom('<!doctype html><html></html>');
global.window = document.defaultView;
global.navigator = window.navigator;

var Foo = React.createClass({
    displayName: "Foo",

    render: function () {
         return React.createElement("head", null, React.createElement("title", null, "foo"));
     }
});

var foo = TestUtils.renderIntoDocument(React.createElement(Foo, null));

var titleElement = TestUtils.findRenderedDOMComponentWithTag(foo, 'title');

console.log(titleElement.getDOMNode().textContent);
```

* Running this with react 0.12.2, correctly logs the text content of the title:
```
$ npm i react@0.12.2
$ node test.js
$ foo
```
* Running this with react 0.13.0 throws a TypeError `undefined is not a function`
```
$ npm i react@0.13.0
$ node test.js
$ /MyProject/node_modules/react/lib/ReactTestUtils.js:110
    return internalInstance._renderedComponent.getPublicInstance();
                                               ^
TypeError: undefined is not a function
    at Object.ReactTestUtils.getRenderedChildOfCompositeComponent (/MyProject/node_modules/react/lib/ReactTestUtils.js:110:48)
    at Object.ReactTestUtils.findAllInRenderedTree (/MyProject/node_modules/react/lib/ReactTestUtils.js:141:26)
    at Object.ReactTestUtils.findAllInRenderedTree (/MyProject/node_modules/react/lib/ReactTestUtils.js:140:24)
    at Object.ReactTestUtils.scryRenderedDOMComponentsWithTag (/MyProject/node_modules/react/lib/ReactTestUtils.js:187:27)
    at Object.ReactTestUtils.findRenderedDOMComponentWithTag (/MyProject/node_modules/react/lib/ReactTestUtils.js:200:30)
    at Object.<anonymous> (/MyProject/test.js:22:30)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

### PR DESCRIPTION
**Pull request by zpao**
#3421 surfaced and looked like a general issue but that didn't make much sense since we use those methods. It turns out it's specific to a couple types of DOM components, specifically the ones we wrap with composite components to add warnings for full page rendering.

Fixes #3421.

### CODE REVIEW

File: src/test/__tests__/ReactTestUtils-test.js [hunk 1]
```diff
@@ -206,4 +206,28 @@ describe('ReactTestUtils', function() {
 
     expect(console.warn.calls.length).toBe(0);
   });
+
+  it('should suppor injected wrapper components as DOM components', function() {
```
Comment (spicyj) [inline src/test/__tests__/ReactTestUtils-test.js]: support

File: src/test/__tests__/ReactTestUtils-test.js [hunk 2]
```diff
@@ -206,4 +206,28 @@ describe('ReactTestUtils', function() {
...
+      'iframe',
+      'img',
+      'input',
+      'option',
+      'select',
+      'textarea',
+      'html',
+      'head',
+      'body'
+    ]
```
Comment (spicyj) [inline src/test/__tests__/ReactTestUtils-test.js]: ;

**Comment by zpao** [comment]
amended
