### ISSUE TITLE
Bug with find* and scry* methods in TestUtils with React 0.13.0

### ISSUE THREAD

**Issue by lo1tuma** [facebook/react#3421]
I’ve tried to update from react 0.12.2 to 0.13.0 which caused several unit tests of my project to fail. I use react to render html on the server side, this includes the basic html structure like `<head>`, `<title>` and `<base>` elements. All unit tests dealing with such elements are failing with react 0.13.0 but they worked fine with 0.12.2.

Here is a minimal example `test.js`:
```js
'use strict';

var React = require('react'),
    ReactAddons = require('react/addons'),
    TestUtils = ReactAddons.addons.TestUtils,
    jsdom = require('jsdom');

global.document = jsdom.jsdom('<!doctype html><html></html>');
global.window = document.defaultView;
global.navigator = window.navigator;

var Foo = React.createClass({
    displayName: "Foo",

    render: function () {
         return React.createElement("head", null, React.createElement("title", null, "foo"));
     }
});

var foo = TestUtils.renderIntoDocument(React.createElement(Foo, null));

var titleElement = TestUtils.findRenderedDOMComponentWithTag(foo, 'title');

console.log(titleElement.getDOMNode().textContent);
```

* Running this with react 0.12.2, correctly logs the text content of the title:
```
$ npm i react@0.12.2
$ node test.js
$ foo
```
* Running this with react 0.13.0 throws a TypeError `undefined is not a function`
```
$ npm i react@0.13.0
$ node test.js
$ /MyProject/node_modules/react/lib/ReactTestUtils.js:110
    return internalInstance._renderedComponent.getPublicInstance();
                                               ^
TypeError: undefined is not a function
    at Object.ReactTestUtils.getRenderedChildOfCompositeComponent (/MyProject/node_modules/react/lib/ReactTestUtils.js:110:48)
    at Object.ReactTestUtils.findAllInRenderedTree (/MyProject/node_modules/react/lib/ReactTestUtils.js:141:26)
    at Object.ReactTestUtils.findAllInRenderedTree (/MyProject/node_modules/react/lib/ReactTestUtils.js:140:24)
    at Object.ReactTestUtils.scryRenderedDOMComponentsWithTag (/MyProject/node_modules/react/lib/ReactTestUtils.js:187:27)
    at Object.ReactTestUtils.findRenderedDOMComponentWithTag (/MyProject/node_modules/react/lib/ReactTestUtils.js:200:30)
    at Object.<anonymous> (/MyProject/test.js:22:30)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by zpao** [comment]
I think this is just a bug, not an intentional breaking change. Thanks for reporting.
