### ISSUE TITLE
`scryRenderedDOMComponentsWithClass` broke between 0.14-rc1 and 0.14

### ISSUE THREAD

**Issue by globexdesigns** [facebook/react#5076]
The `scryRenderedDOMComponentsWithClass` function isn't quite working for me anymore after upgrading from 0.14-rc1 and 0.14.

```
import ReactTestUtils from 'react-addons-test-utils';

const definition = (
	<Spinner text={text} />
);

const spinner = ReactTestUtils.renderIntoDocument(definition);

// This line fails
ReactTestUtils.findRenderedDOMComponentWithClass(spinner, 'ui-spinner');
```

The error stack looks something like this:

```
TypeError: ReactDOM.findDOMNode(...).className.split is not a function
    at http://localhost:8080/build/spec.js:29942:63
    at findAllInRenderedTreeInternal (http://localhost:8080/build/spec.js:29828:14)
    at findAllInRenderedTreeInternal (http://localhost:8080/build/spec.js:29837:25)
    at findAllInRenderedTreeInternal (http://localhost:8080/build/spec.js:29840:23)
    at Object.ReactTestUtils.findAllInRenderedTree (http://localhost:8080/build/spec.js:29928:13)
    at Object.ReactTestUtils.scryRenderedDOMComponentsWithClass (http://localhost:8080/build/spec.js:29940:28)
    at ReactTestUtils.findRenderedDOMComponentWithClass (http://localhost:8080/build/spec.js:29958:31)
    at Object.<anonymous> (http://localhost:8080/build/spec.js:51892:17)
    at attemptSync (http://localhost:8080/test/jasmine-2.2.0/jasmine.js:1741:24)
    at QueueRunner.run (http://localhost:8080/test/jasmine-2.2.0/jasmine.js:1729:9)
```

**Comment by spicyj** [comment]
Can you post a minimal repro case please?

**Comment by globexdesigns** [comment]
The minimal repro for me is this:

```
    var Wrapper = React.createClass({
      render: function() {
        return (
          <div className="x">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg">
              <text>Evgueni</text>
            </svg>
          </div>
        );
      },
    });
    var renderedComponent = ReactTestUtils.renderIntoDocument(<Wrapper />);
    var findResults = ReactTestUtils.findRenderedDOMComponentWithClass(
      renderedComponent,
      'x'
    );
    expect(ReactDOM.findDOMNode(findResults).innerHTML).toContain('Evgueni');
```

If I use an `<svg/>` element -- I get the error reported above. If I use a `<span/>` element -- there is no error.

I tried dropping this as a Jest test in the React source code -- but it passed. However, running this exact same test in my local project -- it fails. I've confirmed that all React libs are 0.14. Could there be some kind of build process that's causing the issue?

**Comment by spicyj** [comment]
Sounds like what @ericf mentioned here: https://github.com/facebook/react/commit/e9c571acc6c87c7b1d14db1635f36bba7082d192#commitcomment-13650087.

**Comment by globexdesigns** [comment]
@spicyj Indeed. Looks like this is the same issue. I hope you can push that out fix in 0.14.1 soon as this is a blocking issue for my team for upgrading to 0.14. Thanks for the fast response.

**Comment by spicyj** [comment]
We'll try. In the meantime, you could copy the definition from here since it doesn't rely on any React internals:

https://github.com/facebook/react/blob/4fb39ce9842811b39314503874b56d925bd28a09/src/test/ReactTestUtils.js#L181
