### ISSUE TITLE
Build Failing with: 'Error: Cannot find module 'react/src/ReactCurrentOwner'

### ISSUE THREAD

**Issue by citisolo** [facebook/react#12681]
**Do you want to request a *feature* or report a *bug*?**
report a bug

**What is the current behavior?**
I've cloned the repo onto my desktop and run `yarn build ` produces the following output;

> Error: Cannot find module 'react/src/ReactCurrentOwner'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.keys.forEach.srcModule (/home/redbandit/src/javascript/newReact/scripts/rollup/plugins/use-forks-plugin.js:35:15)
    at Array.forEach (<anonymous>)
    at useForks (/home/redbandit/src/javascript/newReact/scripts/rollup/plugins/use-forks-plugin.js:32:22)
    at getPlugins (/home/redbandit/src/javascript/newReact/scripts/rollup/build.js:229:5)
    at createBundle (/home/redbandit/src/javascript/newReact/scripts/rollup/build.js:384:14)
    at buildEverything (/home/redbandit/src/javascript/newReact/scripts/rollup/build.js:495:11)
    at \<anonymous\>

it's definitely an issue with my environment because it builds fine on my laptop and I am running the same system on them both

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
N/A

**What is the expected behavior?**
The code should build successfully

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
The version of react is 16,  OS: Ubuntu 16.04 . It works on my laptop which also runs 16.04

**Comment by citisolo** [comment]
I did run run `yarn`. the version is 1.0.1

**Comment by gaearon** [comment]
We depend on Yarn 1.3.2+, please update.
