### ISSUE TITLE
Cryptic error message for findDOMNode of unmounted component

### ISSUE THREAD

**Issue by jimfb** [facebook/react#4233]
As per https://github.com/facebook/react/issues/2410#issuecomment-115659185: findDOMNode(this) throws for unmounted components, but the error message is too cryptic:

`Uncaught Error: Invariant Violation: Component (with keys: getDOMNode,_handleChange,props,context,state,refs,_reactInternalInstance) contains render method but is not mounted in the DOM`

Some expert React users honestly thought they had duplicate React or something, so didn't even bother to check whether the component was mounted. (It wasn't.)

**Comment by saemchou** [comment]
@jimfb I have this exact problem. Did you find a solution?

**Comment by saemchou** [comment]
My problem was that I was using an old version of React.js.

I was using `findDOMNode(reference)` to grab a DOM element. This function is part of the new syntax introduced as of React v0.14 Beta 1. The version of React I am working with is v0.13.3 which still relies on the `getDOMNode()` function.

**Comment by dmatteo** [comment]
@saemchou actually 0.13 already uses `React.findDOMNode(ref)`
0.14 is only different in the sense it's using `ReactDOM`, like: `ReactDOM.findDOMNode(ref)`

**Comment by saemchou** [comment]
Hi @dmatteo thank you for joining, there's still a lot for me to learn about React

I understood that `findDOMNode()` was introduced in 0.14 from the last paragraph of [this blog post](https://facebook.github.io/react/blog/2015/07/03/react-v0.14-beta-1.html).
Also I'm getting the `Uncaught TypeError: React.findDOMNode is not a function` error with React v0.13.3.

I replicated [this example](https://facebook.github.io/react/docs/working-with-the-browser.html) to test the above using npm for dependency management and browserify to bundle everything. Could I be missing something?

**Comment by dmatteo** [comment]
It's hard to know without seeing your code, but my best guess is that you're trying to access `React.findDOMNode()` on 0.14, which doesn't exist because it has been "moved" in `ReactDOM`.

Maybe it's easier for you to start with 0.13 before moving to 0.14 which has this implicit separation of the DOM functions?

**Comment by saemchou** [comment]
@dmatteo yep, I got caught out by the separation of the DOM functions. I managed to get it working on 0.14 now.

I did try using `react` and `react-dom` on 0.14 before but still got the above error (I should have mentioned this). However I found that this was because I was still using `React.render(<Mycomponent />, node)` instead of the correct way `ReactDOM.render(<Mycomponent />, node)`. I corrected this and everything is working now.

I will publish my code next time, I realise it would save a lot of time.

**Comment by dmatteo** [comment]
It usually helps :)
I'm glad you figured it out though.

>

**Comment by percyhanna** [comment]
For any who may happen to run across this same error in the future, I recently saw this error which was caused by calling `getDOMNode()` on a component that had been unmounted. This was caused by an asynchronous event that then assumed the component was still mounted. Although [`isMounted` is considered an anti-pattern](https://facebook.github.io/react/blog/2015/12/16/ismounted-antipattern.html), this is one possible use case that I see it being very convenient for.

**Comment by gaearon** [comment]
@percyhanna Are you saying that you’ve had this error in 0.14.x despite a wording change in #4727? Can you provide a failing test? Thanks.

**Comment by percyhanna** [comment]
I was merely documenting the problem I ran into and its solution, since it seemed to be slightly different than the issues described above. This was on an app that hasn't gotten around to upgrading past 0.13.x yet.

**Comment by gaearon** [comment]
>This was on an app that hasn't gotten around to upgrading past 0.13.x yet.

Got it, thanks. I was just worried we missed some case when adding a warning.
