### ISSUE TITLE
keymirror module not found error

### ISSUE THREAD

**Issue by htettwin** [facebook/react#5201]
Hi,
I'm using the tutorial https://scotch.io/tutorials/creating-a-simple-shopping-cart-with-react-js-and-flux.
It works in 0.13 version but in 0.14 version require('react/lib/keyMirror') no longer works. I updated the code to use require('keymirror') as in the todo example but this also is returning "Cannot find module 'keymirror'"

**Comment by samerbuna** [comment]
I think it has been moved to fbjs, so you could require('fbjs/lib/keyMirror')

**Comment by zpao** [comment]
@samerbuna is correct. It was never an official api,just an internal runtime dependency, so the removal never was included in any change logs.

Fwiw, the key mirror use in that tutorial is completely extraneous - simply assuming values to the constants is enough.
