### PR TITLE
Don't break on SVG tags in scryRenderedDOMComponentsWithClass

### LINKED ISSUE #5076: `scryRenderedDOMComponentsWithClass` broke between 0.14-rc1 and 0.14
The `scryRenderedDOMComponentsWithClass` function isn't quite working for me anymore after upgrading from 0.14-rc1 and 0.14.

```
import ReactTestUtils from 'react-addons-test-utils';

const definition = (
	<Spinner text={text} />
);

const spinner = ReactTestUtils.renderIntoDocument(definition);

// This line fails
ReactTestUtils.findRenderedDOMComponentWithClass(spinner, 'ui-spinner');
```

The error stack looks something like this:

```
TypeError: ReactDOM.findDOMNode(...).className.split is not a function
    at http://localhost:8080/build/spec.js:29942:63
    at findAllInRenderedTreeInternal (http://localhost:8080/build/spec.js:29828:14)
    at findAllInRenderedTreeInternal (http://localhost:8080/build/spec.js:29837:25)
    at findAllInRenderedTreeInternal (http://localhost:8080/build/spec.js:29840:23)
    at Object.ReactTestUtils.findAllInRenderedTree (http://localhost:8080/build/spec.js:29928:13)
    at Object.ReactTestUtils.scryRenderedDOMComponentsWithClass (http://localhost:8080/build/spec.js:29940:28)
    at ReactTestUtils.findRenderedDOMComponentWithClass (http://localhost:8080/build/spec.js:29958:31)
    at Object.<anonymous> (http://localhost:8080/build/spec.js:51892:17)
    at attemptSync (http://localhost:8080/test/jasmine-2.2.0/jasmine.js:1741:24)
    at QueueRunner.run (http://localhost:8080/test/jasmine-2.2.0/jasmine.js:1729:9)
```

### PR DESCRIPTION
**Pull request by spicyj**
Fixes #5076.

### CODE REVIEW

File: src/test/ReactTestUtils.js [hunk 1]
```diff
@@ -186,9 +184,14 @@ var ReactTestUtils = {
     }
     return ReactTestUtils.findAllInRenderedTree(root, function(inst) {
       if (ReactTestUtils.isDOMComponent(inst)) {
-        var classList = ReactDOM.findDOMNode(inst).className.split(/\s+/);
-        return classNames.every(function(className) {
-          return classList.indexOf(className) !== -1;
+        var className = inst.className;
+        if (!className && typeof className !== 'string') {
```
Comment (jimfb) [inline src/test/ReactTestUtils.js]: Maybe I'm missing something, but this line looks suspicious to me.  Is the boolean of a string ever falsey?

Comment (spicyj) [inline src/test/ReactTestUtils.js]: `''` is. Though now I forget why I wrote it this way.  I think it can just be a typeof check.

**Comment by jimfb** [comment]
:+1:
