### ISSUE TITLE
The callback function of setState faster than real dom render

### ISSUE THREAD

**Issue by xinggangling** [facebook/react#13402]
Hello, dear!
       I have a problem, In my project, I want to get the dom from document.getElementById('password');
but my dom is unrendered untill my modal is opened, like bellow:
`rollback = (fversionId) => {
    this.setState({visible: true, handleType: 'rollback', versionId: fversionId}, () => {
      document.getElementById('password').addEventListener('keydown', (e) => {});
    })
 }`
visible control my modal display, It works well in react@15.3.2; Now i am using react@16.2.0, It tell me addEventListener is not a function, so i have to deal with bellow:
`rollback = () => {
    this.setState({visible: true, handleType: 'release'}, () => {
      console.log('start: ', Date.now()) // start: 1534298785781
      this.timer = setInterval(() => {
        if (document.getElementById('password')) {
          console.log('end: ', Date.now()) // end: 1534298785796
          clearInterval(this.timer);
          document.getElementById('password').addEventListener('keydown', (e) => {});
        } else {
             // todo
        }
      }, 10)
    })
}`
It works well like this; em..., I don't know the reason, I just update my react version. I thy reactDom find dom by refs; I receive the same answer from the browser. I wish get the answer from u

**Comment by gaearon** [comment]
Please provide a complete example. This is not enough to reproduce your problem.

**Comment by xinggangling** [comment]
I raise a example on [](https://codepen.io/anon/pen/PBvOEv) , it work well.
`const { Modal, Button } = antd;

class App extends React.Component {
  state = { visible: false }
  showModal = () => {
    this.setState({
      visible: true,
    }, () => {
      console.log(document.getElementById('test'))
    });
  }
  handleOk = (e) => {
    console.log(e);
    this.setState({
      visible: false,
    });
  }
  handleCancel = (e) => {
    console.log(e);
    this.setState({
      visible: false,
    });
  }
  render() {
    return (
      <div>
        <Button type="primary" onClick={this.showModal}>Open</Button>
        <Modal
          title="Basic Modal"
          visible={this.state.visible}
          onOk={this.handleOk}
          onCancel={this.handleCancel}
        >
          {
              this.state.visible ?
              <p id="test">Some contents...</p>
              :
              null
          }
          <p>Some contents...</p>
          <p>Some contents...</p>
        </Modal>
      </div>
    );
  }
}

ReactDOM.render(<App />, mountNode);`
https://unpkg.com/react@15.x/dist/react.js
https://unpkg.com/react-dom@15.x/dist/react-dom.js
![image](https://user-images.githubusercontent.com/18533687/44148130-81d86c9e-a0c9-11e8-8aed-0dd477de028d.png)

[](https://codepen.io/anon/pen/ZjNaMK) , it doesn't work. it is the same of my project, i think setState callback will be called untill dom is rendered like v15, so i can get the real dom directly, 
but v16 i have to get the dom by setInterval to wait the dom really rendered.

https://cdnjs.cloudflare.com/ajax/libs/react/16.4.2/umd/react.production.min.js
https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.4.2/umd/react-dom.production.min.js
![34621534337192_ pic_hd](https://user-images.githubusercontent.com/18533687/44148855-7e641cb8-a0cc-11e8-855d-d811937147f9.jpg)

one get the dom;
another get null;

(:

**Comment by gaearon** [comment]
This doesn't seem to be a React issue.

Here's an example without Antd, using just React portals. You can see that it works as expected: https://codepen.io/gaearon/pen/dac8528178e2c8774a870438f57b56b9/

Therefore the issue is with how Antd library works with React 16. Please file an issue with that library. Thanks!

**Comment by xinggangling** [comment]
ok,thank you
