### ISSUE TITLE
npm run build in branch 16.8.6

### ISSUE THREAD

**Issue by yellowjian** [facebook/react#15986]
when run (npm run build)
get error:
Error: Cannot find module 'react'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at createBundle (D:\E\study\vscode\react-16.8.6\scripts\rollup\build.js:452:31)
    at buildEverything (D:\E\study\vscode\react-16.8.6\scripts\rollup\build.js:614:11)
error Command failed with exit code 1.

**Comment by threepointone** [comment]
works fine here. are you trying to build react?

**Comment by 526117** [comment]
-------- ข้อความต้นฉบับ --------เรื่อง: [facebook/react] npm run build in branch 16.8.6 (#15986)จาก: yellowjian ถึง: facebook/react สำเนา: Subscribed when run (npm run build)
get error:
Error: Cannot find module 'react'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
at Function.resolve (internal/modules/cjs/helpers.js:30:19)
at createBundle (D:\E\study\vscode\react-16.8.6\scripts\rollup\build.js:452:31)
at buildEverything (D:\E\study\vscode\react-16.8.6\scripts\rollup\build.js:614:11)
error Command failed with exit code 1.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/facebook/react/issues/15986?email_source=notifications\u0026email_token=AKB7KA3KR44XHJSTTX32FU3P4ITGHA5CNFSM4H3I3H4KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G3R7EHQ",
"url": "https://github.com/facebook/react/issues/15986?email_source=notifications\u0026email_token=AKB7KA3KR44XHJSTTX32FU3P4ITGHA5CNFSM4H3I3H4KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G3R7EHQ",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by zhouzhonghao** [comment]
You should use yarn. Please use `yarn install` & `yarn run build` to solve the problem.

**Comment by zhouzhonghao** [comment]
@yellowjian , FYI: https://www.zcfy.cc/original/the-overview-of-the-react-codebase-organization.
Please note that yarn uses `workspaces`(https://classic.yarnpkg.com/en/docs/workspaces/)
