### ISSUE TITLE
replaceState throws away functions in 0.13

### ISSUE THREAD

**Issue by WishCow** [facebook/react#3418]
I'm still learning React, so it's possible I'm misunderstanding something.

I'm trying to use React with Immutable.js, and hit a stumbling block, by upgrading to React 0.13. There is [wiki page](https://github.com/facebook/immutable-js/wiki/Immutable-as-React-state) on the immutable.js repository, that explains how to use immutable as a react state, and it provides the following example (I transpiled it to ES3):

```js
'use strict';

var React = require('react');
var Immutable = require('immutable');

var Component = React.createClass({

  getInitialState: function() {
    return Immutable.Map({count:0});
  },

  handleClick: function() {
    this.replaceState(this.state.update('count', function(v) { return v + 1 }));
  },

  render: function() {
    return (
      <div onClick={this.handleClick}>
        {this.state.get('count')}
      </div>
    );
  }

});

React.render(<Component />, document.body);
```

This works great in 0.12, but in 0.13, you will receive the following error when clicking on the div:
```
TypeError: this.state.get is not a function
this.state.get('count')
```
Putting a breakpoint on the error, and inspecting this.state with a debugger reveals that all the methods on this.state have disappeared.

Is this the expected behavior in 0.13?

**Comment by syranide** [comment]
@WishCow `this.state` should be a plain object, you're not allowed to put classes in there.

**Comment by WishCow** [comment]
So the wiki page I linked to is incorrect?

**Comment by syranide** [comment]
@WishCow Seems so... cc @leebyron @sebmarkbage

**Comment by wmertens** [comment]
@WishCow I encountered the same thing in 0.12, storing an immutable-js object on the state directly clobbers it,but simply putting it under an attribute works fine. E.g. `state.foo = myImmutableObject`.

**Comment by jeffutter** [comment]
I am experiencing this after upgrading to 0.13 as well. It didn't seem to be a problem in react 0.12. It seems to almost make sense that state could be an immutable object since equality comparison is cheap. I could nest my state object under state (this.state.state? yuck) but it seems like it would create a lot of boilerplate code that I didn't need in 0.12

**Comment by gaearon** [comment]
I think you can +1 in https://github.com/facebook/react/issues/3303

**Comment by Zenwolf** [comment]
Yeah this bit me bad... I used an immutable.map as all my state and not a plain object, which worked absolutely great in 0.12 and broke in 0.13. This forces me to add a bunch of useless vanilla objects with a single child prop to hold my immutable map.

**Comment by pherris** [comment]
Since I was working with a simple map structure, toObject saved me... e.g.
```
var MyComponent = React.createClass({
  mixins: [PureRenderMixin],
  getInitialState(){
    return MyStore.getState().toObject();
  },
  ...
});
```
Not sure how well this work with more complex object structures however.

**Comment by jeffutter** [comment]
Has there been any movement on this? My project has been on hold since I don't know if I should: a.) stay on React 0.12 where I could use Immutable maps for state. b.) Move all my immutable maps to child of a single-item map. or c.) leave things as they are and this will be supported in the future.

**Comment by syranide** [comment]
@jeffutter AFAIK this is not going to change. Personally I still don't understand why people want to put third-party objects as state, I don't see what benefit there is. What's wrong with just using `setState`?

**Comment by jeffutter** [comment]
@syranide For me there were two main advantages.

1.) My stores already deal in immutable hashes, With react 0.12 I didn't have to bother converting them
2.) Deep comparison for updates is _simple_ with immutable objects. With react 0.12 when you setState with an immutable object, if _any_ of it's contents had changed, it would re-render. If it was the same, it would not. Comparing immutable objects is cheap. Deep comparing hashes is not. There is more upfront cost with the immutable objects, but they are way easier to reason about wether or not they have changed.

If there is definitely no plan to support this then I suppose the best plan of action is to to_js everything and manually deep compare?

**Comment by sebmarkbage** [comment]
There is movement on #3303 which would get rid of replaceState and add better immutable-js support (and perhaps other libraries) in the core.

However, it was not our intention to break the old behavior of replaceState in 0.13 so this seems like a bug to me.

@zpao @spicyj Do we maybe want to patch release this if there is an easy fix?

**Comment by syranide** [comment]
@jeffbski 
1) I can't speak for this, but using a store's data for the singular state object seems rather limiting, you're now unable to include any other stores or introduce any other locally relevant state for the component right?

2) Is straight-forward with objects as well, immutability is not a concept that is unique to *immutable-js*. Depending on the underlying implementation you can use just `===` or a simple reusable shallow equality test with plain objects too.

@sebmarkbage But does #3303 actually intend to allow replacing the "state object" vs just simply understanding how to iterate over generic maps/sets?

**Comment by jeffutter** [comment]
@syranide 

1.) Yes, I do have some components that use data from multiple stores, and those end up as different elements under a hash. When I have a component that only uses the data from one store, it is sort of silly to have it nested as a single element in a hash.

2.) "you can use just === or a simple reusable shallow equality test with plain objects too" is my point exactly, usually my objects are just one level deep and this is fine. I sometimes they are not though and with Immutable-js objects I can use === with deeply nested objects. If I use immutable-js for everything, I don't have to worry about it.

**Comment by zpao** [comment]
@sebmarkbage not sure that it will be the cleanest thing. This is a result of your `ReactUpdateQueue` changes #2930. Right now we just have a `pendingStateQueue` but we don't know what each thing in the queue is (did it come from a `setState` or `replaceState`). We could wrap each item in the queue so we know what it came from, so instead of `[state, state]` we have `[{state: state, is: 'set'}, {state: state, is: 'replace'}]`. That would allow us to stack `setState` and `replaceState` calls (which I don't think we actually handle correctly now).

But the simplest case where you're only using `replaceState`, we can probably just change this line: https://github.com/facebook/react/blob/master/src/core/ReactCompositeComponent.js#L626.

```js
// BEFORE
var nextState = assign({}, replace ? queue[0] : inst.state);
// AFTER (maintain identity of queue[0])
var nextState = replace ? queue[0] : assign({}, inst.state);
```

**Comment by zpao** [comment]
We could take something in 0.13.4 (not 0.13.3, shipping that today). But it needs to bake first. Both changes I mentioned would change behavior so there's some risk. The first is more complete, the latter trades 1 bug for a slightly less bad bug (setState(), replaceState() in the same update queue will result in the object passed to setState being used as the replacement since we only have a single pendingReplace flag)

**Comment by sebmarkbage** [comment]
Actually, this came from #2991. There is a simple fix:

```js
if (replace && queue.length === 1) {
  return queue[0];
}
```

https://github.com/facebook/react/blob/master/src/core/ReactCompositeComponent.js#L625

Because the queue is emptied for every replaceState, since nothing earlier in the queue could've affected the result:

https://github.com/facebook/react/blob/master/src/core/ReactUpdateQueue.js#L177

**Comment by zpao** [comment]
Ah, truth. @spicyj is fixing and it's small and let's just take it in 0.13.3 so we don't have to do another patch release so soon after.

**Comment by mikew** [comment]
So, the issue was fixed in `replaceState`, but what about components using `class Foo extends React.Component {}`?

I'm seeing this when I use `setState`

**Comment by spicyj** [comment]
setState merges. Using a non-plain object with it isn't supported. You can put whatever object you want on an inner state key (this.state.data, this.state.map, etc.).
