### PR TITLE
[Fizz] Restore `useMemoCache` in renderers with support for Client APIs

### PR DESCRIPTION
**Pull request by eps1lon**
e.g. in `react-dom/server`: https://codesandbox.io/p/sandbox/usememocache-react-dom-server-nkz4zc?file=%2Fsrc%2Findex.js%3A9%2C1

Broke only recently in https://github.com/facebook/react/pull/31767. No stable release is affected

## Summary

Mainly an oversight since we don't have types based off of feature flags. Now that `enableUseMemoCache` is shipped, `useMemoCache` can be non-nullable.

Discovered during integration testing with Next.js where SSR threw with `TypeError: dispatcher.useMemoCache is not a function` but ultimately recovered due to client-side rendering.

## How did you test this change?

Hardened types.

### CODE REVIEW

File: packages/react-server/src/ReactFizzHooks.js [hunk 1]
```diff
@@ -834,6 +834,7 @@ export const HooksDispatcher: Dispatcher = supportsClientAPIs
       useActionState,
       useFormState: useActionState,
       useHostTransitionStatus,
+      useMemoCache,
```
Comment (dai-shi) [inline packages/react-server/src/ReactFizzHooks.js:837]: Should `useCacheRefresh` be added here too or not?

Comment (eps1lon) [reply packages/react-server/src/ReactFizzHooks.js:837]: See https://github.com/facebook/react/pull/32068
